'Apple Search Ads'
  , 'blindferret_int'
  , 'blindferret2_int'
  , 'Facebook Ads'
  , 'googleadwords_int'
  , 'liftoff_int'
  , 'reddit_int'
  , 'restricted'
  , 'snapchat_int'
  , 'tapjoy_int'
  , 'facebook' --smart banner input from utm_source
  , 'google'
  , 'snapchat'
  , 'af_facebook'
  , 'bytedanceglobal_int'