--no-cache
select 
    sum(DATEDIFF('second', starttime, endtime)), 
    CASE
    WHEN DATEDIFF('second', starttime, endtime) < 60 THEN '<=60'
    ELSE '>60'
    END as duration
from admin.stl_query_history
where querytxt like '%Query generated by Periscope Data%'
and querytxt not like '%"query_source":"app_supercache"%'
and querytxt like '%"user_email":%'
and starttime >= DATE_TRUNC('day',sysdate) - 7
group by duration
order by duration